#!/bin/bash
DAEMON=/usr/bin/git
USER=git
GROUP=git
BASE_PATH=/repos/
ARGS="daemon --user=$USER --group=$GROUP --reuseaddr --detach --base-path=$BASE_PATH $BASE_PATH --export-all --enable=receive-pack" 
PNAME=git-daemon

start () {
	$DAEMON $ARGS &
}

stop () {
	pkill $PNAME
}

restart() {
	stop
	start
}

case $1 in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo $"Usage: $prog {start|stop|restart}"
        exit 3
        ;;
esac

exit
